# -*- coding: utf-8 -*-

MDL_BYTE = 1
MDL_UNSIGNED_BYTE = 2
MDL_SHORT = 3
MDL_UNSIGNED_SHORT = 4
MDL_HALF = 5
MDL_INT = 6
MDL_UNSIGNED_INT = 7
MDL_FLOAT = 8
MDL_DOUBLE = 9

MDL_FILE = 1
MDL_NODE = 2
MDL_MESH = 3
MDL_BONE = 4
MDL_VERTEXARRAY = 5
MDL_INDICEARRAY = 6
MDL_PROPERTIES = 7
MDL_ANIMATIONKEYS = 8
MDL_AABB = 9
MDL_SURFACE = 10
MDL_NEWTONCOLLISIONTREE = 11

MDL_POSITION = 1
MDL_NORMAL = 2
MDL_TEXTURE_COORD = 3
MDL_COLOR = 4
MDL_TANGENT = 5
MDL_BINORMAL = 6
MDL_BONEINDICE = 7
MDL_BONEWEIGHT = 8

MDL_POINTS = 1
MDL_LINE_STRIP = 2
MDL_LINE_LOOP = 3
MDL_LINES = 4
MDL_TRIANGLE_STRIP = 5
MDL_TRIANGLE_FAN = 6
MDL_TRIANGLES = 7
MDL_QUAD_STRIP = 8
MDL_QUADS = 9
MDL_POLYGON = 10

MDL_VERSION = 1